### ISSUE TITLE
bug in your code 

### ISSUE THREAD

**Issue by NicolaasVanRenne** [ZJUFanLab/SpaTrio#2]
There is a bug in spatrio.R line 55

```
# find python
  if (!file.exists("/home/yph/anaconda3/envs/spatrio/bin/python")) {
    stop("Please enter the correct python path")
```

should be altered to 

```
# find python
if (!file.exists(py_path)) {
    stop("Please enter the correct python path")
```

Otherwise he will never find python path because you hardcoded it. Only took me two days to figure this out.

**Comment by Paul-YPH** [comment]
I am very sorry for the inconvenience caused by the mistake. The relevant code has been corrected.
Thank you again for your reminder!
